name: Build and Release

on:
  push:
    branches: [main]  # Triggers on direct push or PR merge to main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Build with esbuild
      run: |
        cd pkg
        npm run build

    - name: Create or Update Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest Build
        artifacts: pkg/dist/mim.cjs
        body: |
          Automated build from commit: ${{ github.sha }}

          Download: `mim.cjs`
        allowUpdates: true
        prerelease: false
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}